---
- name: Validate parameters
  run_once: true
  assert:
    that:
      - tty_clock.repo is defined 
      - tty_clock.dest is defined 
    quiet: true

- name: Check if installed
  stat:
    path: /usr/local/bin/tty-clock
  register: tty_clock_bin

- name: Build from source
  block:
    - name: Clone project repository
      git:
        repo: "{{ 'https://' + tty_clock.repo }}"
        dest: "{{ tty_clock.dest }}" 
        depth: 1
      register: clone

    - name: Build from source 
      command: /usr/bin/make
      args:
        chdir: "{{ tty_clock.dest }}"

    - name: Copy binary
      copy:
        src: "{{ tty_clock.dest + '/tty-clock' }}" 
        dest: /usr/local/bin
        remote_src: true
        mode: +x

    - name: Remove local project repository
      file:
        path: "{{ tty_clock.dest }}" 
        state: absent
  when:
    - not tty_clock_bin.stat.exists
