---
- name: Validate parameters
  run_once: true
  assert:
    that:
      - ncmpcpp.config.dir is defined
      - ncmpcpp.config.attr.ncmpcpp_directory
      - ncmpcpp.config.attr.mpd_music_dir
      - ncmpcpp.config.attr.lyrics_directory
      - ncmpcpp.config.bindings.next_column is defined
      - ncmpcpp.config.bindings.previous_column is defined
      - ncmpcpp.config.bindings.scroll_up is defined
      - ncmpcpp.config.bindings.scroll_down is defined
    quiet: true

- name: Update APT cache & install package 
  apt:
    update_cache: true
    state: latest
    pkg:
      - ncmpcpp

- name: Create necessary directories
  become_user: "{{ user }}"
  file:
    path: "{{ ncmpcpp.config.dir }}" 
    state: directory

- name: Render config from template
  become_user: "{{ user }}"
  template:
    src: "{{ item + '.j2' }}"
    dest: "{{ ncmpcpp.config.dir + '/' + item }}"
  loop:
    - config
    - bindings
