---
- name: install | validate parameters
  run_once: true
  assert:
    that:
      - ncmpcpp.config.dir is defined
    quiet: true

- name: install | apt install
  apt:
    update_cache: true
    state: latest
    pkg:
      - ncmpcpp

- name: install | create necessary directories
  become_user: "{{ user }}"
  file:
    path: "{{ ncmpcpp.config.dir }}" 
    state: directory

- name: install | deploy configuration files 
  become_user: "{{ user }}"
  copy:
    src: "{{ item }}"
    dest: "{{ ncmpcpp.config.dir + '/' + item }}"
  loop:
    - config
    - bindings
