---
- name: configure | validate task list parameters
  run_once: true
  assert:
    that:
      - qutebrowser.config.dir is defined
    quiet: true

- name: configure | set default web browser 
  alternatives:
    name: x-www-browser 
    link: /usr/bin/x-www-browser
    path: /usr/bin/qutebrowser
    priority: 50

- name: configure | apply local user configurations
  become_user: "{{ user }}"
  block:
    - name: configure | create necessary directories
      file:
        path: "{{ qutebrowser.config.dir }}"
        state: directory

    - name: configure | deploy config file
      copy:
        src: "{{ item }}" 
        dest: "{{ qutebrowser.config.dir }}" 
      loop:
        - config.py
        - nord-qutebrowser.py
