---
- name: install | validate task list parameters
  run_once: true
  assert:
    that:
    quiet: true

- name: install | install package updates
  apt:
    state: latest
    pkg:
      - qutebrowser
  notify:
    - apt-get clean

- name: install | update fonts
  apt:
    state: latest
    pkg:
      - fonts-jetbrains-mono
  notify:
    - fc-cache
    - apt-get clean
