---
- block:
    - import_tasks: "install.yml"
      tags:
        - crt-install 
        - cool-retro-term-install
    - import_tasks: "configure.yml"
      tags:
        - crt-configure 
        - cool-retro-term-configure
  rescue:
    - meta: flush_handlers
  tags:
    - crt
    - cool-retro-term
