---
- name: kernel | validate task list parameters
  run_once: true
  assert:
    that:
      - hardening.kernel is defined
    quiet: true

- name: kernel | set sysctl parameters 
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/local.conf
    reload: true
  when:
    - item.value
  loop: "{{ hardening.kernel | dict2items }}"
