---
- name: Validate parameters
  run_once: true
  assert:
    that:
      - user is defined
      - compton.config.dir is defined

- name: Update APT cache & install package
  apt:
    update_cache: true
    state: latest
    pkg:
      - compton

- name: Deploy configurations
  become_user: "{{ user }}"
  block:
    - name: Create necessary directories
      file:
        path: "{{ item }}" 
        state: directory
      loop:
        - "{{ compton.config.dir }}"
        - ~/.config/autostart

    - name: Render config from template
      template:
        src: "compton.conf.j2" 
        dest: "{{ compton.config.dir }}/compton.conf"

    - name: Enable autostart 
      copy:
        src: compton.desktop
        dest: ~/.config/autostart

    - name: XFCE-specific tasks
      block:
        - name: Check if xfwm default compositor is enabled
          command: xfconf-query -c xfwm4 -p /general/use_compositing
          changed_when: false
          register: xfwm_default_compositor

        - name: Disable xfwm default compositor
          command: xfconf-query -c xfwm4 -p /general/use_compositing -s false  
          when:
            - xfwm_default_compositor.stdout | bool 
      when:
        - '"kali-desktop-xfce" in ansible_facts.packages'
