---
- name: Validate parameters
  run_once: true
  assert:
    that:
      - gotop.repo is defined 
      - gotop.dest is defined 
    quiet: true

- name: Check if installed
  stat:
    path: /usr/local/bin/gotop
  register: gotop_bin

- name: Build from source
  block:
    - name: Clone project repository
      git:
        repo: "{{ 'https://' + gotop.repo }}"
        dest: "{{ gotop.dest }}" 
        depth: 1
        single_branch: true
      register: clone

    - name: Execute build script 
      command: ./scripts/download.sh
      args:
        chdir: "{{ gotop.dest }}"

    - name: Copy binary
      copy:
        src: "{{ gotop.dest + '/gotop' }}" 
        dest: /usr/local/bin
        remote_src: true
        mode: +x

    - name: Remove local project repository
      file:
        path: "{{ gotop.dest }}" 
        state: absent
  when:
    - not gotop_bin.stat.exists
