---
hardening:
  banner: 
    text: |
  ssh:
    Port: 2222
    Banner: /etc/issue.net
    Ciphers: aes256-ctr,aes192-ctr,aes128-ctr
    Protocol: 2
    PermitEmptyPasswords: "no"
    UsePAM: "yes"
    ClientAliveCountMax: 1
    ClientAliveInterval: 300
    MACs: hmac-sha2-512,hmac-sha2-256
    PermitUserEnvironment: "no"
    X11Forwarding: "no"
    X11UseLocalHost: "yes"
    LogLevel: VERBOSE
    IgnoreRhosts: "yes"
    HostbasedAuthentication: "no"
    AllowTcpForwarding: "no"
    GSSAPIAuthentication: "no"
    Compression: "no"
    MaxAuthTries: 3
    MaxSessions: 2
    TCPKeepAlive: "no"
    AllowAgentForwarding: "no"
    AllowUsers: kali
    AllowGroups: kali
  sysctl:
    # dev.tty.ldisc_autoload: 0
    # fs.protected_fifos: 2
    # fs.protected_hardlinks: 1
    # fs.protected_regular: 2
    # fs.protected_symlinks: 1
    # fs.suid_dumpable: 0
    # kernel.panic: 10
    # kernel.core_uses_pid: 1
    # kernel.ctrl-alt-del: 0
    # kernel.dmesg_restrict: 1
    # kernel.kptr_restrict: 2
    # kernel.modules_disabled: 1
    # kernel.perf_event_paranoid: 3
    # kernel.randomize_va_space: 2
    # kernel.sysrq: 0
    # kernel.unprivileged_bpf_disabled: 1
    # kernel.yama.ptrace_scope: 1
    # net.core.bpf_jit_harden: 2
    net.ipv4.ip_forward: 0 
    net.ipv4.conf.all.accept_redirects: 0
    net.ipv4.conf.all.accept_source_route: 0
    net.ipv4.conf.all.bootp_relay: 0
    net.ipv4.conf.all.forwarding: 0
    net.ipv4.conf.all.log_martians: 1
    net.ipv4.conf.all.mc_forwarding: 0
    net.ipv4.conf.all.proxy_arp: 0
    net.ipv4.conf.all.rp_filter: 1
    net.ipv4.conf.all.send_redirects: 0
    net.ipv4.conf.default.accept_redirects: 0
    net.ipv4.conf.default.accept_source_route: 0
    net.ipv4.conf.default.log_martians: 1
    net.ipv4.icmp_echo_ignore_broadcasts: 1
    net.ipv4.icmp_ignore_bogus_error_responses: 1
    net.ipv4.tcp_syncookies: 1
    net.ipv4.tcp_timestamps: 0
    net.ipv6.conf.all.disable_ipv6: 1
    net.ipv6.conf.default.disable_ipv6: 1
    net.ipv6.conf.lo.disable_ipv6: 1
    net.ipv6.conf.all.accept_redirects: 0
    net.ipv6.conf.all.accept_source_route: 0
    net.ipv6.conf.default.accept_redirects: 0
    net.ipv6.conf.default.accept_source_route: 0
