---
- name: install | validate task list parameters
  run_once: true
  assert:
    that:
    quiet: true

- name: install | install package updates
  apt:
    state: latest
    pkg:
      - ranger
      - caca-utils
      - highlight
      - atool
      - w3m
      - poppler-utils
      - mediainfo
  notify:
    - apt-get clean
