---
- block:
    - import_tasks: "install.yml"
      tags:
        - ranger-install
    - import_tasks: "configure.yml"
      tags:
        - ranger-configure
  rescue:
    - meta: flush_handlers
  tags:
    - ranger
