---
- name: install | validate task list parameters
  run_once: true
  assert:
    that:
      - nitrogen.user != ""
      - nitrogen.config.dir is defined

- name: install | apt install
  apt:
    update_cache: true
    state: latest
    pkg:
      - nitrogen

- name: install | create necessary directories
  become_user: "{{ nitrogen.user }}"
  file:
    path: "{{ nitrogen.config.dir }}" 
    state: directory

- name: install | render dotfiles from template
  become_user: "{{ nitrogen.user }}"
  template:
    src: "{{ item[0] }}" 
    dest: "{{ nitrogen.config.dir }}/{{ item[1] }}"
  with_together:
    - ["nitrogen.cfg.j2","bg-saved.cfg.j2"]
    - ["nitrogen.cfg","bg-saved.cfg"]
  notify: nitrogen --restore 
