---
mpd:
  config:
    dir: "~/.config/mpd"
    attr:
      playlist_directory: "~/.mpd/playlists"
      music_directory: "~/Music"
      db_file: "~/.mpd/mpd.db"
      log_file: "~/.mpd/mpd.log"
      pid_file: "~/.mpd/mpd.pid"
      state_file: "~/.mpd/mpdstate"
