---
- name: Validate parameters
  run_once: true
  assert:
    that:
      - user is defined
      - dircolors.theme.nord.repo is defined
      - dircolors.theme.nord.dest is defined
    quiet: true
    
- name: Clone project repository
  become_user: "{{ user }}"
  git:
    repo: "{{ 'https://' + dircolors.theme.nord.repo }}"
    dest: "{{ dircolors.theme.nord.dest }}"
    force: true
    depth: 1
    single_branch: true
  changed_when: false

- name: Copy source file to user home directory 
  become_user: "{{ user }}"
  copy:
    src: "{{ dircolors.theme.nord.dest + '/src/dir_colors' }}"
    dest: ~/.dir_colors
    remote_src: true

- name: Remove install artifacts
  file:
    path: "{{ dircolors.theme.nord.dest }}" 
    state: absent
  changed_when: false

- name: Activate 
  become_user: "{{ user }}"
  lineinfile:
    path: ~/.zshrc 
    state: present
    line: test -r ~/.dir_colors && eval $(dircolors ~/.dir_colors) 
    insertafter: EOF
