---
- name: Gather package facts 
  package_facts:
    manager: apt
  async: 3600
  poll: 0
  check_mode: false
  changed_when: false
  register: installed_packages

- name: Wait to gather package facts 
  async_status:
    jid: "{{ installed_packages.ansible_job_id }}"
  until: job_result.finished
  retries: 10
  delay: 3
  check_mode: false
  register: job_result
