---
- name: install | validate task list parameters
  run_once: true
  assert:
    that:
    quiet: true

- name: install | install package updates
  apt:
    state: latest
    pkg:
      - zathura
      - zathura-pdf-poppler
      - zathura-ps
      - zathura-cb
      - zathura-djvu
  notify:
    - apt-get clean
