---
- block:
    - import_tasks: "install.yml"
      tags:
        - zathura-install
    - import_tasks: "configure.yml"
      tags:
        - zathura-configure
  rescue:
    - meta: flush_handlers
  tags:
    - zathura
