---
- block:
    - import_tasks: "install.yml"
      tags:
        - rofi-install
    - import_tasks: "configure.yml"
      tags:
        - rofi-configure
  rescue:
    - meta: flush_handlers
  tags:
    - rofi
