---
- name: configure | validate task list parameters
  run_once: true
  assert:
    that:
      - mpd.config.dir is defined
    quiet: true

- name: configure | apply local user configurations 
  become_user: "{{ user }}"
  block:
    - name: configure | create necessary directories
      file:
        path: "{{ item }}" 
        state: directory
      loop:
        - "{{ mpd.config.dir }}"
        - ~/.mpd/playlists
        - ~/Music

    - name: configure | create necessary files
      file:
        path: "{{ item }}" 
        state: touch
      changed_when: false
      loop:
        - "{{ mpd.config.attr.db_file }}"
        - "{{ mpd.config.attr.log_file }}"
        - "{{ mpd.config.attr.pid_file }}"
        - "{{ mpd.config.attr.state_file }}"

    - name: configure | render config from template
      template:
        src: "mpd.conf.j2"
        dest: "{{ mpd.config.dir + '/mpd.conf' }}"

    - name: configure | start & enable service with user scope
      systemd:
        name: mpd
        state: started
        enabled: true
        scope: user
