---
- name: install | validate parameters
  run_once: true
  assert:
    that:
      - mpd.config.dir is defined
      - mpd.config.attr.playlist_directory
      - mpd.config.attr.music_directory
      - mpd.config.attr.db_file
      - mpd.config.attr.log_file
      - mpd.config.attr.pid_file
      - mpd.config.attr.state_file
    quiet: true

- name: install | apt install
  apt:
    update_cache: true
    state: latest
    pkg:
      - mpd

- name: install | create necessary directories
  become_user: "{{ user }}"
  file:
    path: "{{ item }}" 
    state: directory
  loop:
    - "{{ mpd.config.dir }}"
    - "{{ mpd.config.attr.playlist_directory }}"
    - "{{ mpd.config.attr.music_directory }}"

- name: install | create necessary files
  become_user: "{{ user }}"
  file:
    path: "{{ item }}" 
    state: touch
  changed_when: false
  loop:
    - "{{ mpd.config.attr.db_file }}"
    - "{{ mpd.config.attr.log_file }}"
    - "{{ mpd.config.attr.pid_file }}"
    - "{{ mpd.config.attr.state_file }}"

- name: install | render config from template
  become_user: "{{ user }}"
  template:
    src: "mpd.conf.j2"
    dest: "{{ mpd.config.dir + '/mpd.conf' }}"
