---
- block:
    - import_tasks: "install.yml"
      tags:
        - discord-install
    - import_tasks: "configure.yml"
      tags:
        - discord-configure
  rescue:
    - meta: flush_handlers
  tags:
    - discord
