---
- block:
    - import_tasks: "install.yml"
      tags:
        - cava-install
    - import_tasks: "configure.yml"
      tags:
        - cava-configure
  rescue:
    - meta: flush_handlers
  tags:
    - cava
