---
- name: install | validate task list parameters
  run_once: true
  assert:
    that:
      - neofetch.config.dir is defined
    quiet: true

- name: install | apt install
  apt:
    update_cache: true
    state: latest
    pkg:
      - neofetch

- name: install | create necessary directories
  become_user: "{{ user }}"
  file:
    path: "{{ neofetch.config.dir }}" 
    state: directory

- name: install | render config from template
  become_user: "{{ user }}"
  template:
    src: "config.conf.j2"
    dest: "{{ neofetch.config.dir + '/config.conf' }}"
