---
- block:
    - import_tasks: "install.yml"
      tags:
        neofetch-install
    - import_tasks: "configure.yml"
      tags:
        neofetch-configure
  rescue:
    - meta: flush_handlers
  tags:
    - neofetch
