---
- block:
    - import_tasks: "install.yml"
      tags:
        - alacritty-install
    - import_tasks: "configure.yml"
      tags:
        - alacritty-configure
  rescue:
    - meta: flush_handlers
  tags:
    - alacritty
