---
- name: Ensure host is Kali Linux 
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Validate parameters
      run_once: true
      assert:
        that:
          - user is defined
        quiet: true

    - name: Group by distribution
      group_by:
        key: "{{ ansible_distribution }}"
      changed_when: false
  tags:
    - always

- name: Deploy custom configuration 
  hosts: Kali
  become: true
  gather_facts: false
  handlers:
    - import_tasks: "{{ playbook_dir + '/includes/handlers.yml' }}"
  pre_tasks:
    - block:
        - name: Gather package facts 
          package_facts:
            manager: apt

        - name: Gather service facts
          service_facts:

        - name: Update APT cache
          apt:
            update_cache: true
      tags:
        - always
  roles:
    - alacritty
    - bpytop
    - cava
    - compton
    - crt
    - dircolors
    - discord
    - latex
    - lightdm
    - mpd
    - ncmpcpp
    - neofetch
    - neovim
    - qutebrowser
    - ranger
    - rofi
    - rustscan
    - tty-clock
    - virtualbox
    - xfce
    - zathura
    - zsh
  tasks:
    - name: install misc tools
      apt:
        state: latest
        pkg: 
          - antiword
          - bettercap
          - cmatrix
          - dc3dd
          - docx2txt
          - evil-winrm
          - gdb
          - gdb-doc
          - gobuster
          - hydra
          - python3-impacket
          - jq
          - libsox-fmt-all
          - lynis
          - ncat
          - ncdu
          - nmap
          - ndiff
          - nuclei
          - nvidia-cuda-toolkit
          - nvidia-driver
          - rkhunter
          - seclists
          - sox
          - sqlmap
          - strace
          - tree
      tags:
        - misc-tools
      notify:
        - apt-get clean
