---
- name: Ensure host is Kali Linux 
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Group by distribution
      group_by:
        key: "{{ ansible_distribution }}"
      changed_when: false
  tags:
    - always

- name: Deploy custom configuration 
  hosts: Kali
  become: true
  gather_facts: false
  vars:
    includes_dir: "{{ playbook_dir + '/includes' }}"
  handlers:
    - import_tasks: "{{ includes_dir + '/handlers.yml' }}"
  pre_tasks:
    - block:
        - import_tasks: "{{ includes_dir + '/package_facts.yml' }}"
        - import_tasks: "{{ includes_dir + '/service_facts.yml' }}"
      tags:
        - always
  roles:
    - alacritty
    - compton
    - dircolors
    - discord
    - gotop
    - misc-utils
    - neofetch
    - neovim
    - qutebrowser
    - ranger
    - tty-clock
  post_tasks:
    - block:
        - import_tasks: "{{ includes_dir + '/dist_upgrade.yml' }}"
      tags:
        - always
