---
- name: install | validate task list parameters
  run_once: true
  assert:
    that:
    quiet: true

- name: install | install package updates
  apt:
    state: latest
    pkg:
      - python3-pip 
      - neovim 
  notify:
    - apt-get clean

- name: install | remove Vim, Emacs, Nano, and Cherrytree
  apt:
    pkg:
      - vim 
      - vim-athena
      - vim-common
      - vim-doc
      - vim-gtk
      - vim-gtk3
      - vim-gui-common
      - vim-nox
      - vim-tiny
      - nano
      - emacs
      - cherrytree
    state: absent
    purge: true
    autoremove: true

- name: install | remove leftover artifacts
  file:
    path: "{{ item }}" 
    state: absent
  loop:
    - /usr/bin/vim
    - /usr/share/vim
    - /etc/emacs
    - /usr/share/emacs
